import React, { useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { Download, Maximize2, Share2, Sparkles, X, Check, SlidersHorizontal, Wand2, AlertTriangle, RefreshCw } from 'lucide-react'

interface RowanImageCardProps {
  imageUrl: string
  prompt: string
  provider?: string
  onRegenerate?: (
    prompt: string,
    options?: {
      aspectRatio?: '1:1' | '16:9' | '9:16' | '4:3' | '3:4'
      styleIntent?: string
      refineFromPrevious?: boolean
      previousPrompt?: string
      refinementInstruction?: string
      previousImageUrl?: string
    }
  ) => void
  theme?: 'dark' | 'light'
}

type AspectRatioType = '1:1' | '16:9' | '9:16' | '4:3' | '3:4'
type StyleIntentType = 'photorealistic' | 'commercial' | 'product' | 'portrait' | '3d_render' | 'vector_illustration' | 'general'

export const RowanImageCard: React.FC<RowanImageCardProps> = ({
  imageUrl,
  prompt,
  provider,
  onRegenerate,
  theme = 'dark'
}) => {
  const [isZoomed, setIsZoomed] = useState(false)
  const [copied, setCopied] = useState(false)
  const [showControls, setShowControls] = useState(false)
  const [imageError, setImageError] = useState(false)
  const [imageLoading, setImageLoading] = useState(true)
  
  // Customization state
  const [aspectRatio, setAspectRatio] = useState<AspectRatioType>('1:1')
  const [styleIntent, setStyleIntent] = useState<StyleIntentType>('general')
  const [refinementInstruction, setRefinementInstruction] = useState('')

  const isDark = theme === 'dark'

  const handleDownload = async () => {
    try {
      const response = await fetch(imageUrl)
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `rowan-image-${Date.now()}.jpg`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
    } catch {
      window.open(imageUrl, '_blank')
    }
  }

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Generated by Rowan AI',
          text: prompt,
          url: imageUrl
        })
        return
      } catch {
        // Fallback to copy
      }
    }

    await navigator.clipboard.writeText(imageUrl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleApplyCustomizations = () => {
    if (!onRegenerate) return
    
    const hasRefinement = refinementInstruction.trim().length > 0
    onRegenerate(prompt, {
      aspectRatio,
      styleIntent,
      refineFromPrevious: hasRefinement,
      previousPrompt: prompt,
      refinementInstruction: hasRefinement ? refinementInstruction : undefined,
      previousImageUrl: hasRefinement ? imageUrl : undefined
    })
    
    // Reset instruction after applying
    setRefinementInstruction('')
    setShowControls(false)
  }

  return (
    <div className="my-4 space-y-2 select-none max-w-md w-full">
      {/* 1. IMAGE CONTAINER */}
      <div
        className={`relative rounded-2xl overflow-hidden border transition-all shadow-lg group min-h-[220px] flex items-center justify-center ${
          isDark ? 'bg-slate-950 border-slate-800/80 hover:border-blue-500/40' : 'bg-zinc-50 border-zinc-200'
        }`}
      >
        {imageLoading && !imageError && (
          <div className="absolute inset-0 flex items-center justify-center bg-slate-950/60 backdrop-blur-sm z-10">
            <div className="w-6 h-6 border-2 border-blue-400 border-t-transparent rounded-full animate-spin" />
          </div>
        )}

        {imageError ? (
          <div className="p-6 text-center space-y-3 my-auto">
            <div className="w-10 h-10 rounded-full bg-rose-500/10 border border-rose-500/20 text-rose-400 flex items-center justify-center mx-auto">
              <AlertTriangle className="w-5 h-5" />
            </div>
            <div>
              <p className="text-xs font-semibold text-rose-400">Unable to render image</p>
              <p className="text-[11px] text-zinc-400 mt-1">Image URL failed to load or expired</p>
            </div>
            {onRegenerate && (
              <button
                type="button"
                onClick={() => {
                  setImageError(false)
                  setImageLoading(true)
                  onRegenerate(prompt)
                }}
                className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center gap-1.5 mx-auto transition-colors cursor-pointer"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Retry Generation</span>
              </button>
            )}
          </div>
        ) : (
          <img
            src={imageUrl}
            alt={prompt}
            className="w-full h-auto object-contain cursor-pointer transition-transform duration-350 group-hover:scale-[1.01]"
            onClick={() => setIsZoomed(true)}
            onLoad={() => setImageLoading(false)}
            onError={() => {
              setImageLoading(false)
              setImageError(true)
            }}
            loading="lazy"
          />
        )}

        {/* Hover action overlay */}
        {!imageError && (
          <div className="absolute inset-0 bg-slate-950/45 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 pointer-events-none">
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                setIsZoomed(true)
              }}
              className="p-2 rounded-full bg-slate-900/95 text-white hover:bg-blue-600 transition-colors pointer-events-auto shadow-md"
              title="Expand image"
            >
              <Maximize2 className="w-4 h-4" />
            </button>
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation()
                handleDownload()
              }}
              className="p-2 rounded-full bg-slate-900/95 text-white hover:bg-blue-600 transition-colors pointer-events-auto shadow-md"
              title="Download image"
            >
              <Download className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Neural Engine Badge */}
        <div className="absolute top-2 left-2 flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-slate-950/80 backdrop-blur-md text-[10px] font-black tracking-wide text-blue-400 border border-blue-500/35 uppercase">
          <Sparkles className="w-2.5 h-2.5" />
          <span>{provider || 'AI Engine'}</span>
        </div>
      </div>

      {/* 2. PROMPT & ACTIONS FOOTER */}
      <div className="flex items-center justify-between gap-3 px-1">
        <p className={`text-xs italic truncate flex-grow ${isDark ? 'text-zinc-400' : 'text-zinc-600'}`}>
          "{prompt}"
        </p>

        <div className="flex items-center gap-1 flex-shrink-0">
          {onRegenerate && (
            <button
              type="button"
              onClick={() => setShowControls(!showControls)}
              className={`p-1.5 rounded-lg transition-colors cursor-pointer ${
                showControls
                  ? 'bg-blue-600/20 text-blue-400 border border-blue-500/30'
                  : isDark
                  ? 'text-zinc-450 hover:text-white hover:bg-slate-800'
                  : 'text-zinc-600 hover:text-zinc-900 hover:bg-zinc-200'
              }`}
              title="Refine image properties"
            >
              <SlidersHorizontal className="w-3.5 h-3.5" />
            </button>
          )}

          <button
            type="button"
            onClick={handleDownload}
            className={`p-1.5 rounded-lg transition-colors cursor-pointer ${
              isDark ? 'text-zinc-450 hover:text-white hover:bg-slate-800' : 'text-zinc-600 hover:text-zinc-900 hover:bg-zinc-200'
            }`}
            title="Download image"
          >
            <Download className="w-3.5 h-3.5" />
          </button>

          <button
            type="button"
            onClick={handleShare}
            className={`p-1.5 rounded-lg transition-colors cursor-pointer ${
              isDark ? 'text-zinc-450 hover:text-white hover:bg-slate-800' : 'text-zinc-600 hover:text-zinc-900 hover:bg-zinc-200'
            }`}
            title="Share image"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5" />}
          </button>
        </div>
      </div>

      {/* 3. EXPANDABLE PREMIUM CUSTOMIZATION CONTROLS PANEL */}
      <AnimatePresence>
        {showControls && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className={`rounded-2xl p-4 border overflow-hidden space-y-3.5 ${
              isDark ? 'bg-slate-900/40 border-slate-800 text-zinc-100' : 'bg-zinc-50 border-zinc-200 text-zinc-800'
            }`}
          >
            {/* Aspect Ratio Selector */}
            <div className="space-y-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Aspect Ratio</span>
              <div className="flex flex-wrap gap-1.5">
                {(['1:1', '16:9', '9:16', '4:3', '3:4'] as AspectRatioType[]).map((ratio) => (
                  <button
                    key={ratio}
                    type="button"
                    onClick={() => setAspectRatio(ratio)}
                    className={`px-2.5 py-1 text-2xs font-bold rounded-lg transition-all cursor-pointer border ${
                      aspectRatio === ratio
                        ? 'bg-blue-600 border-blue-500 text-white'
                        : isDark
                        ? 'bg-slate-900 border-slate-800 text-zinc-400 hover:text-zinc-200'
                        : 'bg-white border-zinc-200 text-zinc-600 hover:bg-zinc-100'
                    }`}
                  >
                    {ratio}
                  </button>
                ))}
              </div>
            </div>

            {/* Style Intent Selector */}
            <div className="space-y-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Art Style Intent</span>
              <div className="flex flex-wrap gap-1.5">
                {[
                  { id: 'general', label: 'Default' },
                  { id: 'photorealistic', label: 'Photorealistic' },
                  { id: 'commercial', label: 'Commercial' },
                  { id: 'product', label: 'Product Shot' },
                  { id: 'portrait', label: 'Portrait' },
                  { id: '3d_render', label: '3D Render' },
                  { id: 'vector_illustration', label: 'Vector Art' }
                ].map((style) => (
                  <button
                    key={style.id}
                    type="button"
                    onClick={() => setStyleIntent(style.id as StyleIntentType)}
                    className={`px-2.5 py-1 text-2xs font-bold rounded-lg transition-all cursor-pointer border ${
                      styleIntent === style.id
                        ? 'bg-blue-600 border-blue-500 text-white'
                        : isDark
                        ? 'bg-slate-900 border-slate-800 text-zinc-400 hover:text-zinc-200'
                        : 'bg-white border-zinc-200 text-zinc-600 hover:bg-zinc-100'
                    }`}
                  >
                    {style.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Text-based prompt refinement instruction input */}
            <div className="space-y-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-400 block">
                Refine Prompt (Optional)
              </span>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={refinementInstruction}
                  onChange={(e) => setRefinementInstruction(e.target.value)}
                  placeholder="e.g., 'Make it night time', 'Add golden rain'..."
                  className={`flex-grow px-3 py-1.5 text-xs font-medium rounded-xl border focus:outline-none focus:ring-1 ${
                    isDark
                      ? 'bg-slate-950 border-slate-800 focus:border-blue-500 focus:ring-blue-500/20 text-white placeholder-zinc-600'
                      : 'bg-white border-zinc-200 focus:border-blue-500 focus:ring-blue-500/20 text-zinc-800 placeholder-zinc-400'
                  }`}
                />
              </div>
            </div>

            {/* Apply Button */}
            <button
              type="button"
              onClick={handleApplyCustomizations}
              className="w-full py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 cursor-pointer shadow-md shadow-blue-600/15 transition-all"
            >
              <Wand2 className="w-3.5 h-3.5" />
              <span>Apply & Generate</span>
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* 4. LIGHTBOX MODAL */}
      <AnimatePresence>
        {isZoomed && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md"
            onClick={() => setIsZoomed(false)}
          >
            <div
              className="relative max-w-2xl w-full flex flex-col items-center gap-3"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                type="button"
                onClick={() => setIsZoomed(false)}
                className="absolute -top-10 right-0 p-2 rounded-full bg-slate-800 text-white hover:bg-slate-700 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>

              <img
                src={imageUrl}
                alt={prompt}
                className="max-h-[80vh] w-auto rounded-2xl shadow-2xl object-contain border border-slate-800"
              />

              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-lg transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download Image</span>
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
